### ISSUE TITLE
关于restful一定不能使用session有点太武断了，jwt虽然有一定优势但是也存在一定的劣势。

### ISSUE THREAD

**Issue by cly00** [whvcse/EasyWeb#1]

**Comment by whvcse** [comment]
“一定”确实有点武断，已更正，关于session和jwt的对比也是各有所长，但是在RESTful中肯定是不能使用session作为登录的验证方式，可以存储其他数据，像app的项目，登录需要持久化，使用时间比较长，session需要传递cookie与之对应，可能app关掉再打开就不是一个cookie了，并且session的过期时间较短，不适合于app，RESTful后端肯定是多平台支持(不分客户端)
